### ISSUE TITLE
Update the DG: user stories, glossary, NFRs, use cases

### ISSUE THREAD

**Issue by sheehui** [AY2122S1-CS2103T-W16-1/tp#14]
### Complete the following. Refer to tP week 7, point 4 for more info.
- [x] Target user profile
- [x] value proposition
- [x] user stories:
- [x] Use cases
  - Give use cases (textual form) for a few representative user stories that need multiple steps to complete. e.g. Adding a tag to a person (assume the user needs to find the person first)
- [x] Non-functional requirements
  - Note: Many of the given project constraints can be considered NFRs. You can add more. e.g. performance requirements, usability requirements, scalability requirements, etc.
- [x] Glossary: Define terms that are worth recording.

**Comment by sheehui** [comment]
Target user profile, value proposition and user stories updated in #28

**Comment by bharathcs** [comment]
Fixed by #49 and #48
