### ISSUE TITLE
Remarks should be allowed to be empty for `Liability` and `Assets`

### ISSUE THREAD

**Issue by sheehui** [AY2122S1-CS2103T-W16-1/tp#174]

**Comment by Bluntsord** [comment]
@bharathcs @sheehui how do u guys want to do this again. Rmb yall were talking about it. Should we accept null or smth

**Comment by bharathcs** [comment]
I'm scared of nulls honestly. What if we just auto fill in "" if append is called without a remark prefix?

**Comment by Bluntsord** [comment]
So the same way notes is done? I think that should be the way as well @sheehui ?

**Comment by sheehui** [comment]
making remarks optional will be considered a new feature, thus this issue will not be pursued further.

[Damith's words](https://github.com/nus-cs2103-AY2122S1/forum/issues/366#issuecomment-957141989)
