### ISSUE TITLE
[PE-D] Editing of name does not work (or at least it's not clear how it works)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W16-1/tp#251]
![image.png](https://raw.githubusercontent.com/BenjaminLHR/ped/main/files/72357d79-5666-49c6-a563-3cfb50a81806.png)

![image.png](https://raw.githubusercontent.com/BenjaminLHR/ped/main/files/2789bdc9-9d76-4372-af71-8633d0745998.png)

I tried the following two commands, both in home tab and within the contact tab, but both failed to work. Not sure if I have misunderstood the UG.

I was following this instruction as well:

Faced similar issue for editing of address, phone, email etc.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: BenjaminLHR/ped#9

**Comment by bharathcs** [comment]
Fixed by #199
