### ISSUE TITLE
[PE-D] Overzealous input validation for phone and name fields

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W16-1/tp#265]
![image.png](https://raw.githubusercontent.com/BenjaminLHR/ped/main/files/51a71b3c-b792-4094-9d60-14e0d5eb90dd.png)

The phone field does not support things like "+" for country code or any non-numerical characters (and that is perhaps somewhat overzealous)

Similarly, I am unable to input "add n/De'Aaron Fox p/98765432 e/johnd@example.com a/John street, block 123, #01-01" as the name is deemed invalid.

![image.png](https://raw.githubusercontent.com/BenjaminLHR/ped/main/files/dbc0a23b-51f9-4f29-a511-729df939c685.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: BenjaminLHR/ped#14

**Comment by bharathcs** [comment]
Closed. Feature flaw, not bug. And its up for discussion.
