### ISSUE TITLE
[PE-D] Flagged as invalid command format for delete although used in the right format

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W16-1/tp#271]
![image.png](https://raw.githubusercontent.com/BenjaminLHR/ped/main/files/bc61c93e-63a4-457b-9cd9-154bee25bbec.png)

I believe this has to do with the value exceeding MAX_INT as I get a different message if I type something like "delete 100"

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: BenjaminLHR/ped#18

**Comment by bharathcs** [comment]
LOL

**Comment by sheehui** [comment]
so dumb eh sian
