### ISSUE TITLE
[PE-D] Long inputs are truncated

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W16-1/tp#272]
![image.png](https://raw.githubusercontent.com/BenjaminLHR/ped/main/files/44573edb-4f6e-4192-ae98-0a4d22d94a9f.png)

The overly-long address of index 13 is truncated

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: BenjaminLHR/ped#19

**Comment by bharathcs** [comment]
I believe we don't need the home view to work so hard as to have such an enthusiastic specification of addresses. Out of scope.

**Comment by bharathcs** [comment]
Reopened for anyone to self-assign if its an easy fix.
