### ISSUE TITLE
[PE-D] Edit command might not work as intended

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W16-1/tp#275]
The edit command does not edit any fields of the person added. I tested out each fields (from address, name, contacts, and also email). If you type in only `edit _prefix_/` it would work as intended. The error message is updated accordingly as well. However, when you type in the value e.g. `edit n/John Doe` it will return the error message `Please enter a valid prefix`. I tried out the input from the user guide as well and it is still not working. Here is a short capture of what I tested.
![Screenshot (573).png](https://raw.githubusercontent.com/HalphasX/ped/main/files/5b29d6ec-eea9-4f08-bbb0-07bfdfa563a4.png)

![Screenshot (572).png](https://raw.githubusercontent.com/HalphasX/ped/main/files/c6ac2f12-2be2-4aed-8a4f-f43704df0d05.png)

![Screenshot (574).png](https://raw.githubusercontent.com/HalphasX/ped/main/files/14f4d628-f187-424b-a821-b268052cb69d.png)

![Screenshot (575).png](https://raw.githubusercontent.com/HalphasX/ped/main/files/970ff5be-eabf-4500-bbf7-44ef3a939bb8.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: HalphasX/ped#2

**Comment by bharathcs** [comment]
Fixed by #199
